version: "3.8"

services:
  app:
    container_name: svg-game
    image: node:latest
    restart: always
    command: sh -c "npm install && npm run build:production && npm run start"
    working_dir: /app
    build:
      context: ./
      target: dev
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    networks:
      - frontend
    volumes:
      - ./:/app

networks:
  frontend:

volumes:
  app:
